### ISSUE TITLE
aks create fails when not specifying --node-osdisk-diskencryptionset-id

### ISSUE THREAD

**Issue by hplatou** [Azure/azure-cli-extensions#1187]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### aks create fails when not specifying `--node-osdisk-diskencryptionset-id`

`az aks create -g $RG -n $XXX --node-count 1 --generate-ssh-keys` 

fails with error: 

> Property id '' at path 'properties.diskEncryptionSetID' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.

**Comment by venture27** [comment]
I am also experiencing this problem. Updated az cli to latest 2.0.79 but it had no effect.

My scripts have not changed since December, at which time all commands worked fine to create my cluster.

**Comment by sinelshchikov** [comment]
As a workaround I rolled back to the previous version:
```
az extension remove aks-preview
az extension add --yes --source https://azurecliaks.blob.core.windows.net/azure-cli-extension/aks_preview-0.4.25-py2.py3-none-any.whl && az extension list
```

**Comment by rodrigc** [comment]
@sinelshchikov I ran into this too, but I'm using this:

```
az extension list
[
  {
    "extensionType": "whl",
    "name": "aks-preview",
    "version": "0.4.23"
  }
]
```

and this:

```
rpm -q azure-cli
azure-cli-2.0.79-1.el7.x86_64
```

Do you know what version of the azure-cli-extension has this problem?

**Comment by sinelshchikov** [comment]
@rodrigc , can you check it with 0.4.25 version?

**Comment by jluk** [comment]
FYI @sauryadas / @feiskyer

**Comment by sauryadas** [comment]
@andyzhangx can you please take a look?

**Comment by rodrigc** [comment]
@sinelshchikov I just confirmed, `0.4.25` works for me, `0.4.26` fails for me.

**Comment by andyzhangx** [comment]
looks like this error msg came from azure-cli-extension(since if I use armclient it works well):
```
$ az aks create -g craig-test-1 -n craig-test-1 --node-count 1 --generate-ssh-keys
The behavior of this command has been altered by the following extension: aks-preview
Property id '' at path 'properties.diskEncryptionSetID' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
```

To workaround this issue, just remove `aks-preview` or use `0.4.25` directly.
```
az extension remove --name aks-preview
```

Still figuring out where this error came from, @zikalino @zqingqing1 @qwordy @arrownj do you have any idea? how can I skip 'properties.diskEncryptionSetID' check in  azure-cli-extension?

**Comment by andyzhangx** [comment]
Just found the root cause, just one line of code change, will fix it ASAP.

**Comment by andyzhangx** [comment]
fixed by https://github.com/Azure/azure-cli-extensions/pull/1192

**Comment by hplatou** [comment]
> fixed by #1192

I can confirm that this fixes the problem for me. Thanks!

**Comment by jluk** [comment]
Thank you @andyzhangx - closing.

**Comment by fegonfe** [comment]
this bug is back and I'm not using preview.

az extension list
  {
    "experimental": false,
    "extensionType": "whl",
    "preview": false,
    "version": "0.8.0"
  }

**Comment by eversonamancio** [comment]
Same issue here.

**Comment by FHPIENAAR** [comment]
I ran into the same issue, added the aks-preview extension and I was able to proceed with the deployment.

**Comment by fegonfe** [comment]
as a workaround, I got back to version 2.10.1 and it worked

**Comment by briglx** [comment]
Getting this issue running the workshop tasks https://docs.microsoft.com/en-us/learn/modules/aks-workshop/02-deploy-aks
I'm using docker image of mcr.microsoft.com/azure-cli tools

**Comment by sbugalski** [comment]
I confirm issue. Ran from Azure Cloud Shell.
```
$ az version
{
  "azure-cli": "2.11.0",
  "azure-cli-core": "2.11.0",
  "azure-cli-telemetry": "1.0.5",
  "extensions": {}
}
```

**Comment by InterStelios** [comment]
I can also confirm the issue:

```
azure-cli                         2.11.0

core                              2.11.0
telemetry                          1.0.5

Python location '/usr/local/Cellar/azure-cli/2.11.0/libexec/bin/python'
Extensions directory '/Users/stelios.kiayias/.azure/cliextensions'

Python (Darwin) 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by vnextcoder** [comment]
Same issue faced with Azure CLI 2.11.  But once Workaround Extension installed, it worked fine. 

AZ CLI 2.10 was working fine earlier.

**Comment by andyzhangx** [comment]
latest Azure CLI 2.11.1 works now
